version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8.10
    steps:
      - checkout
      - run:
          name: Set up Python environment
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run PyCaret Server
          command: |
            . venv/bin/activate
            python pycaret_server/app.py
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
