export const dataTypesActionTypes = {
    SET_NUMERIC_FEATURES: "SET_NUMERIC_FEATURES",
    SET_CATEGORICAL_FEATURES: "SET_CATEGORICAL_FEATURES",
    SET_DATE_FEATURES: "SET_DATE_FEATURES",
    SET_IGNORED_FEATURES: "SET_IGNORED_FEATURES",
  };
  