export const missingValuesActionTypes = {
  SET_IMPUTATION_TYPE: "SET_IMPUTATION_TYPE",
  SET_NUMERIC_IMPUTATION: "SET_NUMERIC_IMPUTATION",
  SET_OTHER_NUMERIC_IMPUTATION: "SET_OTHER_NUMERIC_IMPUTATION",
  SET_CATEGORICAL_IMPUTATION: "SET_CATEGORICAL_IMPUTATION",
  SET_OTHER_CATEGORICAL_IMPUTATION: "SET_OTHER_CATEGORICAL_IMPUTATION",
  SET_NUMERIC_ITERATIVE_IMPUTER: "SET_NUMERIC_ITERATIVE_IMPUTER",
  SET_ITERATIVE_IMPUTATION_ITERATIONS: "SET_ITERATIVE_IMPUTATION_ITERATIONS",
  SET_CATEGORICAL_ITERATIVE_IMPUTER: "SET_CATEGORICAL_ITERATIVE_IMPUTER",
};
